### ISSUE TITLE
Инструкция не сохраняется на диск

### ISSUE THREAD

**Issue by Plyushchenko** [ArtyomLobanov/black-jack#1]
При попытке создать инструкцию редактируемой сейчас модели и записать её в отдельный файл она не сохраняется в выбранное пользователем место.

Открыть/создать модель для редактирования.
Выбрать "Создать инструкцию".
Указать желаемую папку в появившемся диалоговом окне.
Нажать "Сохранить".

Ожидание: файлик с инструкцией появится в выбранной папке.
Реальность: его там нет, хотя программа тратит некоторое время на создание инструкции.

Где воспроизводится: все OS, начиная с версии 1.2.3.

**Comment by ArtyomLobanov** [comment]
Баг подтверждён - будем работать

**Comment by ArtyomLobanov** [comment]
@lddqa Подтвердите исправление

**Comment by Denzed** [comment]
Баг больше не воспроизводится.
