### ISSUE TITLE
Вылет при попытке открыть большую модель

### ISSUE THREAD

**Issue by ArtyomLobanov** [ArtyomLobanov/black-jack#4]
При попытке открыть для редактирования большую модель (модель автомобиля в масштабе 1:10) программа вылетает с ошибкой "java.lang.OutOfMemoryError: Java heap space". Размер файла с сохранённой моделью - 46МБ, размер оперативной памяти компьютера - 8ГБ. 
Версия программы - 2.3.9, ОС - Windows 10
Модель доступна по ссылке:  [www.yandex.ru](www.yandex.ru)

**Comment by Denzed** [comment]
Постараемся решить в кратчайшие сроки.

**Comment by Denzed** [comment]
@lddqa, подтвердите отсутствие проблемы.

**Comment by ArtyomLobanov** [comment]
Подтверждаю: проблема больше не воспроизводится
