### ISSUE TITLE
Возможность поставить деталь в редакторе ниже плоскости пола

### ISSUE THREAD

**Issue by Denzed** [ArtyomLobanov/black-jack#7]
Если для перемещения детали пользоваться не мышкой, а клавишами управления курсором, можно опустить деталь пола. Соответственно, после снятия выделения ничего не с ней поделать. Воспроизводится только на OS X не старше El Capitan.

**Comment by Plyushchenko** [comment]
Поправил: https://github.com/ArtyomLobanov/lego-digital-designer/commit/4ff27300d2b95540c92d6f66dfef6984f51278b5
@LDDQA, подтвердите.

**Comment by Plyushchenko** [comment]
lddqa: баг больше не воспроизводится.
